# Generated by Django 4.1 on 2022-08-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinned_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='users',
        ),
    ]
